version: "3"
services:
  influxdb:
    image: influxdb:1.7.2
    ports:
      - "8087:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/backups:/backups
  grafana:
    image: grafana/grafana:5.3.2
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/dashboards-yml:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources-yml:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-default-json:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
