apiVersion: 1

datasources:
- name: My InfluxDB Server
  type: influxdb
  access: proxy
  orgId: 1
  url: http://localhost:8086
  user: admin
  password: admin
  database: mitemp
  isDefault: true
  editable: true
  version: 1
